### ISSUE TITLE
[Rewrite] Update the Openrevolution library to version 2.6.0

### ISSUE THREAD

**Issue by FreeApp2014** [FreeApp2014/BRSTM-cocoa-player#2]
Add support to BRWAV, BCWAV and BFWAV file formats in the player. The formats are already implemented in the library, and will work using the same getbuffer methods

**Comment by ic-scm** [comment]
BCWAV and BFWAV support was added only after 2.6.0, and BRWAV is not supported at all, it's just a placeholder format code

**Comment by FreeApp2014** [comment]
Fixed in [b98f8cd](https://github.com/FreeApp2014/Malugri/commit/b98f8cd82ba9c1168c1da35d99ac74571be307ae)
