### ISSUE TITLE
[Rewrite] BWAV files not working

### ISSUE THREAD

**Issue by FreeApp2014** [FreeApp2014/BRSTM-cocoa-player#3]
When attempting to play a BWAV file, the player just outputs garbage, and the console gets spammed with `brstm_fstream_read: Unexpected end of file.`

**Comment by ic-scm** [comment]
Fixed in [openrevolution 2.7.0](https://github.com/ic-scm/openrevolution/releases/tag/v2.7.0)

**Comment by FreeApp2014** [comment]
Fixed in [b98f8cd](https://github.com/FreeApp2014/Malugri/commit/b98f8cd82ba9c1168c1da35d99ac74571be307ae)
